import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axios from 'axios';

const SubmitAdvertise = () => {
  const [name, setName] = useState('');
  const [websiteUrl, setWebsiteUrl] = useState('');
  const [generationMethod, setGenerationMethod] = useState('toolify');
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    // Check login status when component mounts
    checkLoginStatus();
  }, []);

  const checkLoginStatus = async () => {
    try {
      const response = await axios.get('/api/auth/check-login', {
        withCredentials: true
      });
      
      if (response.data.isLoggedIn) {
        setIsLoggedIn(true);
      } else {
        setIsLoggedIn(false);
      }
    } catch (error) {
      console.error('Error checking login status:', error);
      setIsLoggedIn(false);
    }
  };

  const handlePayment = async (e) => {
    e.preventDefault();
    
    // Check login status before proceeding
    if (!isLoggedIn) {
      // Save form data to session storage before redirecting
      sessionStorage.setItem('paymentFormData', JSON.stringify({
        name,
        websiteUrl,
        generationMethod
      }));
      
      // Redirect to login page
      navigate('/login?redirect=submit_advertise');
      return;
    }
    
    // If logged in, proceed with payment
    try {
      const response = await axios.post('/api/payments/process', {
        name,
        websiteUrl,
        generationMethod,
        amount: 99
      }, { withCredentials: true });
      
      if (response.data.success) {
        // Redirect to payment success page or payment processor
        window.location.href = response.data.paymentUrl;
      }
    } catch (error) {
      console.error('Payment processing error:', error);
      // Handle payment error
    }
  };

  // Restore form data from session storage if returning from login
  useEffect(() => {
    const savedFormData = sessionStorage.getItem('paymentFormData');
    if (savedFormData && isLoggedIn) {
      const parsedData = JSON.parse(savedFormData);
      setName(parsedData.name || '');
      setWebsiteUrl(parsedData.websiteUrl || '');
      setGenerationMethod(parsedData.generationMethod || 'toolify');
      
      // Clear session storage after restoring data
      sessionStorage.removeItem('paymentFormData');
    }
  }, [isLoggedIn]);

  return (
    <div className="max-w-2xl mx-auto p-6 bg-white rounded-lg shadow-md">
      <h1 className="text-2xl font-bold mb-6">Submit Your Tool</h1>
      
      <form onSubmit={handlePayment}>
        <div className="mb-4">
          <label htmlFor="name" className="block text-sm font-medium text-gray-700">
            <span className="text-red-500">*</span> Name
          </label>
          <input
            type="text"
            id="name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-purple-500 focus:ring focus:ring-purple-500 focus:ring-opacity-50"
            placeholder="Copy AI"
            required
          />
        </div>
        
        <div className="mb-4">
          <label htmlFor="websiteUrl" className="block text-sm font-medium text-gray-700">
            <span className="text-red-500">*</span> Website URL
          </label>
          <input
            type="url"
            id="websiteUrl"
            value={websiteUrl}
            onChange={(e) => setWebsiteUrl(e.target.value)}
            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-purple-500 focus:ring focus:ring-purple-500 focus:ring-opacity-50"
            placeholder='Please enter the tool url, such as: "https://www.copy.ai"'
            required
          />
        </div>
        
        <div className="mb-4">
          <p className="block text-sm font-medium text-gray-700 mb-2">
            <span className="text-red-500">*</span> Choose how to generate tool information
          </p>
          
          <div className="space-y-2">
            <label className="flex items-center p-3 border border-gray-300 rounded-md cursor-pointer hover:bg-purple-50">
              <input
                type="radio"
                name="generationMethod"
                value="toolify"
                checked={generationMethod === 'toolify'}
                onChange={() => setGenerationMethod('toolify')}
                className="h-4 w-4 text-purple-600 focus:ring-purple-500"
              />
              <div className="ml-3">
                <p className="text-sm font-medium text-purple-600">Generated by Toolify</p>
                <p className="text-sm text-gray-600">All content and translations are generated by Toolify AI</p>
              </div>
            </label>
            
            <label className="flex items-center p-3 border border-gray-300 rounded-md cursor-pointer hover:bg-purple-50">
              <input
                type="radio"
                name="generationMethod"
                value="myself"
                checked={generationMethod === 'myself'}
                onChange={() => setGenerationMethod('myself')}
                className="h-4 w-4 text-purple-600 focus:ring-purple-500"
              />
              <div className="ml-3 flex justify-between w-full">
                <div>
                  <p className="text-sm font-medium text-gray-900">Do it myself</p>
                  <p className="text-sm text-gray-600">Provide tool information myself in English only, translated by Toolify AI</p>
                </div>
                <span className="bg-yellow-400 text-xs font-bold px-2 py-1 rounded">NEW</span>
              </div>
            </label>
          </div>
        </div>
        
        <div className="mt-8 border-t pt-6">
          <div className="flex justify-between items-center mb-6">
            <div>
              <p className="text-2xl font-bold">Total: $ 99</p>
              <p className="text-sm text-gray-600">No queue, listed within 48 hours</p>
            </div>
            <button
              type="submit"
              className="bg-purple-600 hover:bg-purple-700 text-white px-6 py-3 rounded-md text-lg font-medium"
            >
              Pay $ 99
            </button>
          </div>
        </div>
      </form>
    </div>
  );
};

export default SubmitAdvertise;